print("Conversión de tipos")
print(2 + int("100"))
print("100" + str(2))
print(type(float("3.1416")))
print(int(3.1416))
print(bool(3))
print(bool(0))
print(bool(-1))
print(bool(""))
print(bool(" "))
print(bool("False"))
print(round(2.51))
# print(int("Hola mundo"))